apiVersion: v2
name: cloudbeaver
description: Helm chart for deploying CloudBeaver on Kubernetes
type: application
version: 0.3.2
appVersion: "26.0.3"
kubeVersion: ">=1.23.0-0"
home: https://github.com/zyy17/cloudbeaver-deploy
sources:
  - https://github.com/zyy17/cloudbeaver-deploy
keywords:
  - cloudbeaver
  - database
  - kubernetes
maintainers:
  - name: zyy17
